### ISSUE TITLE
report_score(actual_label, test_pred) function

### ISSUE THREAD

**Issue by fighting41love** [uclmr/fakenewschallenge#1]
Thanks for sharing the code! 
I notice that there is a function named report_score(actual_Label, test_pred) in the https://github.com/FakeNewsChallenge/fnc-1-baseline.
In your code, how can I get the actual_label for test set in the code?
I just learn the tensorflow for a few days.
Hope you can answer my naive question.
Thanks!

**Comment by jaminriedel** [comment]
You are welcome!

Thank you for your question.

The code in this repository was originally uploaded for the organizers of the Fake News Challenge to reproduce our submission. At that point we did not have the labelled test set.

This has been released in the meantime: https://github.com/FakeNewsChallenge/fnc-1/blob/master/competition_test_stances.csv.

You can thus download and work with this file by changing the `file_test_instances` pointer in the '# Set file names' section of `pred.py`. Make sure the new `competition_test_stances.csv` is saved in the same directory!

Hopefully this answers your question :)
