### ISSUE TITLE
Doubt about the TF-IDF cosine

### ISSUE THREAD

**Issue by JoaoLages** [uclmr/fakenewschallenge#2]
In lines 185-186 of  `fakenewschallenge/util.py` you have:
```
tfidf_vectorizer = TfidfVectorizer(max_features=lim_unigram, stop_words=stop_words).\fit(heads + bodies + test_heads + test_bodies) # Train and test sets
```

Isn't this cheating a bit? By that I mean, when testing, shouldn't you calculate the TF-IDF of each single test instance (with all the train instances) instead of grouping all train+test together?

**Comment by jaminriedel** [comment]
The system indeed uses information from the test set during training. This is explicitly stated in the description of the system.

Other systems successful on the Fake News Challenge Stance Detection task do the same or similar. It appears this approach is not against the rules of the official competition.
